=== api-evangelist/wikipedia/json-schema/mediawiki-core-rest-file-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/wikipedia/refs/heads/main/json-schema/mediawiki-core-rest-file-schema.json",
  "title": "File",
  "description": "A media file descriptor.",
  "type": "object",
  "properties": {
    "title": {
      "type": "string",
      "example": "File:Earth_Eastern_Hemisphere.jpg"
    },
    "file_description_url": {
      "type": "string",
      "format": "uri"
    },
    "latest": {
      "type": "object",
      "properties": {
        "timestamp": {
          "type": "string",
          "format": "date-time"
        },
        "user": {
          "type": "object",
          "properties": {
            "id": {
              "type": "integer"
            },
            "name": {
              "type": "string"
            }
          }
        }
      }
    },
    "preferred": {
      "type": "object",
      "properties": {
        "mediatype": {
          "type": "string",
          "example": "BITMAP"
        },
        "size": {
          "type": "integer"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    },
    "original": {
      "type": "object",
      "properties": {
        "mediatype": {
          "type": "string"
        },
        "size": {
          "type": "integer"
        },
        "width": {
          "type": "integer"
        },
        "height": {
          "type": "integer"
        },
        "url": {
          "type": "string",
          "format": "uri"
        }
      }
    }
  }
}

=== api-evangelist/wikipedia/examples/mediawiki-core-rest-file-example.json
{
  "title": "File:Earth_Eastern_Hemisphere.jpg",
  "file_description_url": "https://en.wikipedia.org/wiki/Earth",
  "latest": {
    "timestamp": "2026-05-29T18:21:47Z",
    "user": {
      "id": 9228,
      "name": "Earth"
    }
  },
  "preferred": {
    "mediatype": "BITMAP",
    "size": 12345,
    "width": 9228,
    "height": 720,
    "url": "https://en.wikipedia.org/wiki/Earth"
  },
  "original": {
    "mediatype": "BITMAP",
    "size": 12345,
    "width": 9228,
    "height": 720,
    "url": "https://en.wikipedia.org/wiki/Earth"
  }
}
