=== api-evangelist/wikipedia/json-schema/wikimedia-enterprise-article-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/wikipedia/refs/heads/main/json-schema/wikimedia-enterprise-article-schema.json",
  "title": "article",
  "description": "article schema from Wikimedia Enterprise API spec",
  "type": "object",
  "properties": {
    "event": {
      "$ref": "#/components/schemas/event"
    },
    "additional_entities": {
      "items": {
        "$ref": "#/components/schemas/entity"
      },
      "type": "array"
    },
    "article_body": {
      "$ref": "#/components/schemas/article_body"
    },
    "has_parts": {
      "type": "array",
      "items": {
        "$ref": "#/components/schemas/part"
      }
    },
    "categories": {
      "items": {
        "$ref": "#/components/schemas/category"
      },
      "type": "array"
    },
    "date_modified": {
      "type": "string"
    },
    "identifier": {
      "type": "integer"
    },
    "in_language": {
      "$ref": "#/components/schemas/language"
    },
    "is_part_of": {
      "$ref": "#/components/schemas/project"
    },
    "license": {
      "items": {
        "$ref": "#/components/schemas/license"
      },
      "type": "array"
    },
    "main_entity": {
      "$ref": "#/components/schemas/entity"
    },
    "name": {
      "type": "string"
    },
    "abstract": {
      "type": "string"
    },
    "namespace": {
      "$ref": "#/components/schemas/article_namespace"
    },
    "protection": {
      "items": {
        "$ref": "#/components/schemas/protection"
      },
      "type": "array"
    },
    "redirects": {
      "items": {
        "$ref": "#/components/schemas/redirect"
      },
      "type": "array"
    },
    "templates": {
      "items": {
        "$ref": "#/components/schemas/template"
      },
      "type": "array"
    },
    "url": {
      "type": "string"
    },
    "version": {
      "$ref": "#/components/schemas/version"
    },
    "visibility": {
      "$ref": "#/components/schemas/visibility"
    }
  }
}

=== api-evangelist/wikipedia/examples/wikimedia-enterprise-article-example.json
{
  "event": null,
  "additional_entities": [
    null
  ],
  "article_body": null,
  "has_parts": [
    null
  ],
  "categories": [
    null
  ],
  "date_modified": "Earth",
  "identifier": 9228,
  "in_language": null,
  "is_part_of": null,
  "license": [
    null
  ],
  "main_entity": null,
  "name": "Earth",
  "abstract": "Earth",
  "namespace": null,
  "protection": [
    null
  ],
  "redirects": [
    null
  ],
  "templates": [
    null
  ],
  "url": "https://en.wikipedia.org/wiki/Earth",
  "version": null,
  "visibility": null
}
